### PR TITLE
feat: SAO v2

### PR DESCRIPTION
**Pull request by egoist**
* [x] TypeScript
* [x] Bundle SAO as single files
* [ ] ~~Upgradable template~~ This will be a separate CLI tool https://github.com/saojs/sao/issues/132
* [x] Testing generator
* [x] Show prompts flags in generator help
* [x] Writing docs with docup

<details>
  <summary>📦 Published PR as canary version: <code>1.7.2-canary.145.30b2bdb.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install sao@1.7.2-canary.145.30b2bdb.0
  # or 
  yarn add sao@1.7.2-canary.145.30b2bdb.0
  ```
</details>

### CODE REVIEW

**Comment by niftylettuce** [comment]
Just sponsored you on GH.  Would love to see #132!

**Comment by brpaz** [comment]
Looking forward for the next version.

Some questions:

* Will sao v1 generators be compatible with sao v2?
* Any plans to add something like #137?

I plan to allocate a personal budget for GitHub Sponsors very soon. You will probably be one of the firsts. ;) Love SAO!

**Comment by egoist** [comment]
1. almost, there're some small changes because we replaced inquirer.js with
enquirer, I can write a codemod if needed
2. that feature will be in v2

**Comment by lirantal** [comment]
@egoist are we all good with promoting 1.7.2 as an official release since this has landed in July already...?

**Comment by egoist** [comment]
@lirantal v2 is released under `beta` channel, I need to finish docs before making it the default.

**Comment by lirantal** [comment]
@egoist gotcha 🤗
I didn't go through it. Are the (many) major breaking changes?

Let me know if there's anything I can do to help.

**Pull request merged**
