### PR TITLE
Get template data from cli options

### PR DESCRIPTION
**Pull request by nikolajevp**
#3 #69

### CODE REVIEW

**Comment by nikolajevp** [comment]
Why is it `CLI alias: --yes -y`?

**Comment by egoist** [comment]
@nikolajevp since this actually fixed https://github.com/saojs/sao/issues/69 too

**Comment by egoist** [comment]
Oh I think what I mean in https://github.com/saojs/sao/issues/3 is that we only skip question for `foo` is `--data.foo foo` is set. Anyways this PR did what I want for #69 ..

**Comment by nikolajevp** [comment]
Cool. Thanks!

**Pull request merged**
